#!/bin/bash

# exit on error
set -e

# source debconf library.
#. /usr/share/debconf/confmodule

DIR=/usr/share/laps4linux-runner

# create system-wide venv and install python libraries via pip
python3 -m venv --system-site-packages $DIR/venv
$DIR/venv/bin/pip3 install --upgrade pip==25.0.0 setuptools==80.8.0
$DIR/venv/bin/pip3 install --upgrade $DIR
$DIR/venv/bin/pip3 uninstall -y pip setuptools
